name: Deploy

on: [push, workflow_dispatch]

jobs:
  build-launcher:
    runs-on: ubuntu-22.04
    strategy:
      matrix:
        python-version: [ "3.8" ]
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Set up Python ${{ matrix.python-version }}
        uses: actions/setup-python@v3
        with:
          python-version: ${{ matrix.python-version }}

      - name: Install Python dependencies
        run: |
          python3 -m pip install --upgrade pip
          pip3 install -r requirements.txt

      - name: Build and deploy Continuous Verification Framework
        run: |
          echo "Building and deploying CV..."
          make install -j"$(nproc)" DEPLOY_DIR=build

  build-witness-visualizer:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        python-version: ["3.8"]
    steps:
    - uses: actions/checkout@v3
    - name: Set up Python ${{ matrix.python-version }}
      uses: actions/setup-python@v3
      with:
        python-version: ${{ matrix.python-version }}
    - name: Install dependencies
      run: |
        python3 -m pip install --upgrade pip
        pip3 install -r requirements.txt
    - name: Deployment of Benchmark Visualizer
      run: |
        DEPLOY_DIR=build make install-benchmark-visualizer -j$(nproc)
        cd build
        python3 ./cv/witness_visualizer.py -r results/ -d ../docs/examples/witnesses/violation/
        python3 ./cv/witness_visualizer.py -r results/ -d ../docs/examples/witnesses/correctness/
  build-mea:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        python-version: ["3.8"]
    steps:
    - uses: actions/checkout@v3
    - name: Set up Python ${{ matrix.python-version }}
      uses: actions/setup-python@v3
      with:
        python-version: ${{ matrix.python-version }}
    - name: Install dependencies
      run: |
        python3 -m pip install --upgrade pip
        pip3 install -r requirements.txt
    - name: Deployment of MEA
      run: |
        DEPLOY_DIR=build make install-mea -j$(nproc)
        cd build
        python3 ./cv/mea.py -d ../docs/examples/witnesses/violation/
  deploy-cvv:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        python-version: ["3.8"]
    steps:
    - uses: actions/checkout@v3
    - name: Set up Python ${{ matrix.python-version }}
      uses: actions/setup-python@v3
      with:
        python-version: ${{ matrix.python-version }}
    - name: Install dependencies
      run: |
        python3 -m pip install --upgrade pip
        pip3 install -r requirements.txt
    - name: Deployment of MEA
      run: |
        DEPLOY_DIR=build make deploy-cvv -j$(nproc)
        cd build/cvv
        deploys/deployment.sh
